name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Login to Firebase
      run: firebase login --no-interactive --ci

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
